use football_manager;
CREATE TABLE `team_has_competitions` (
  `id_team_has_competition` int(11) NOT NULL AUTO_INCREMENT,
  `id_team` bigint(20) DEFAULT NULL,
  `id_competitions` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id_team_has_competition`),
  KEY `fk_id_team_idx` (`id_team`),
  KEY `fk_id_competition_idx` (`id_competitions`),
  CONSTRAINT `fk_id_competition` FOREIGN KEY (`id_competitions`) REFERENCES `competitions` (`id_competitions`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_team` FOREIGN KEY (`id_team`) REFERENCES `teams` (`id_teams`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (1,1);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (2,1);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (3,1);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (4,1);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (5,1);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (6,1);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (7,1);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (8,1);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (9,1);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (10,1);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (11,2);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (12,2);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (13,2);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (14,2);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (15,2);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (16,2);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (17,2);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (18,2);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (19,2);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (20,2);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (21,3);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (22,3);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (23,3);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (24,3);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (25,3);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (26,3);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (27,3);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (28,3);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (29,3);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (30,3);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (31,4);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (32,4);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (33,4);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (34,4);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (35,4);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (36,4);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (37,4);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (38,4);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (39,4);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (40,4);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (51,5);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (52,5);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (53,5);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (54,5);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (55,5);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (56,5);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (57,5);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (58,5);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (59,5);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (60,5);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (61,6);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (62,6);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (63,6);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (64,6);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (65,6);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (66,6);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (67,6);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (68,6);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (69,6);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (70,6);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (71,7);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (72,7);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (73,7);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (74,7);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (75,7);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (76,7);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (77,7);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (78,7);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (79,7);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (80,7);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (81,8);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (82,8);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (83,8);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (84,8);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (85,8);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (86,8);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (87,8);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (88,8);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (89,8);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (90,8);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (91,9);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (92,9);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (93,9);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (94,9);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (95,9);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (96,9);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (97,9);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (98,9);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (99,9);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (100,9);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (101,10);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (102,10);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (103,10);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (104,10);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (105,10);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (106,10);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (107,10);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (108,10);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (109,10);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (110,10);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (111,11);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (112,11);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (113,11);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (114,11);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (115,11);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (116,11);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (117,11);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (118,11);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (119,11);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (120,11);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (121,1);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (122,1);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (123,1);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (124,1);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (125,1);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (126,1);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (127,1);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (128,1);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (129,1);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (130,2);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (131,2);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (132,2);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (133,2);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (134,2);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (135,2);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (136,2);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (137,2);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (138,2);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (139,2);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (140,3);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (141,3);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (142,3);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (143,3);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (144,3);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (145,3);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (146,3);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (147,3);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (148,3);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (149,3);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (150,4);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (151,4);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (152,4);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (153,4);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (154,4);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (155,4);
INSERT INTO `team_has_competitions` (`id_team`,`id_competitions`) VALUES (156,4);


INSERT INTO `configs` (`key_name`,`value`,`description`) VALUES ('scorers-to-deliver','2','Scorers a listar por competencia');

